export * from './movie-details.interface'
export * from './popular.interface'
export * from './movie-short.interface'
export * from './genre.interface'
export * from './genres-respons.interface'
export * from './page.interface'
